import type { PiiCategory } from "@/lib/pim/types";

export const GENERALIZATIONS: Record<PiiCategory, string> = {
  email: "[email]",
  phone: "[telefoonnummer]",
  bsn: "[bsn]",
  iban: "[iban]",
  postcode: "[postcode]",
  name: "[persoon]",
  school: "[school]",
  date: "[datum]",
  address: "[adres]",
  student_id: "[leerlingnummer]",
  class_code: "[klas]",
  credit_card: "[creditcard]",
  license_plate: "[kenteken]",
  url: "[link]",
  ip_address: "[ip-adres]",
  social_handle: "[handle]",
  birthdate_text: "[geboortedatum]",
  context_small_group: "[groep]",
  context_care: "[zorgcontext]",
  context_incident: "[incident]",
  context_role: "[rol]",
  context_health: "[gezondheid]",
  context_family: "[gezinscontext]",
  context_legal: "[justitiecontext]",
  context_financial: "[financiële context]",
  context_protected_class: "[bijzondere categorie]",
  context_performance: "[schoolprestatie]",
  context_location_specific: "[locatie]",
};

/** Standaard: harde, ondubbelzinnige identificatoren worden direct gewist. */
export const DEFAULT_AUTO_REDACT: ReadonlySet<PiiCategory> = new Set<PiiCategory>([
  "email", "phone", "bsn", "iban", "credit_card", "postcode",
  "address", "birthdate_text", "student_id", "ip_address",
]);

export const CATEGORY_LABELS: Record<PiiCategory, string> = {
  email: "E-mailadres",
  phone: "Telefoon",
  bsn: "BSN",
  iban: "IBAN",
  postcode: "Postcode",
  name: "Naam",
  school: "School",
  date: "Datum",
  address: "Adres",
  student_id: "Leerlingnummer",
  class_code: "Klascode",
  credit_card: "Creditcard",
  license_plate: "Kenteken",
  url: "Link",
  ip_address: "IP-adres",
  social_handle: "Social handle",
  birthdate_text: "Geboortedatum",
  context_small_group: "Kleine groep",
  context_care: "Zorgcontext",
  context_incident: "Incident",
  context_role: "Rol",
  context_health: "Gezondheid",
  context_family: "Gezinscontext",
  context_legal: "Justitie",
  context_financial: "Financieel",
  context_protected_class: "Bijzondere categorie",
  context_performance: "Schoolprestatie",
  context_location_specific: "Specifieke locatie",
};