/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as IndexRouteImport } from './routes/index'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/compliance': typeof ComplianceRoute
  '/flags': typeof FlagsRoute
  '/modes': typeof ModesRoute
  '/pipeline': typeof PipelineRoute
  '/scenarios': typeof ScenariosRoute
  '/trust': typeof TrustRoute
  '/try': typeof TryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/compliance': typeof ComplianceRoute
  '/flags': typeof FlagsRoute
  '/modes': typeof ModesRoute
  '/pipeline': typeof PipelineRoute
  '/scenarios': typeof ScenariosRoute
  '/trust': typeof TrustRoute
  '/try': typeof TryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architecture': typeof ArchitectureRoute
  '/compliance': typeof ComplianceRoute
  '/flags': typeof FlagsRoute
  '/modes': typeof ModesRoute
  '/pipeline': typeof PipelineRoute
  '/scenarios': typeof ScenariosRoute
  '/trust': typeof TrustRoute
  '/try': typeof TryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architecture'
    | '/compliance'
    | '/flags'
    | '/modes'
    | '/pipeline'
    | '/scenarios'
    | '/trust'
    | '/try'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architecture'
    | '/compliance'
    | '/flags'
    | '/modes'
    | '/pipeline'
    | '/scenarios'
    | '/trust'
    | '/try'
  id:
    | '__root__'
    | '/'
    | '/architecture'
    | '/compliance'
    | '/flags'
    | '/modes'
    | '/pipeline'
    | '/scenarios'
    | '/trust'
    | '/try'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectureRoute: typeof ArchitectureRoute
  ComplianceRoute: typeof ComplianceRoute
  FlagsRoute: typeof FlagsRoute
  ModesRoute: typeof ModesRoute
  PipelineRoute: typeof PipelineRoute
  ScenariosRoute: typeof ScenariosRoute
  TrustRoute: typeof TrustRoute
  TryRoute: typeof TryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectureRoute: ArchitectureRoute,
  ComplianceRoute: ComplianceRoute,
  FlagsRoute: FlagsRoute,
  ModesRoute: ModesRoute,
  PipelineRoute: PipelineRoute,
  ScenariosRoute: ScenariosRoute,
  TrustRoute: TrustRoute,
  TryRoute: TryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
