/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TryRouteImport } from './routes/try'
import { Route as SchrijvenRouteImport } from './routes/schrijven'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTrustRouteImport } from './routes/_site.trust'
import { Route as SiteScenariosRouteImport } from './routes/_site.scenarios'
import { Route as SitePipelineRouteImport } from './routes/_site.pipeline'
import { Route as SiteOverRouteImport } from './routes/_site.over'
import { Route as SiteModesRouteImport } from './routes/_site.modes'
import { Route as SiteFlagsRouteImport } from './routes/_site.flags'
import { Route as SiteComplianceRouteImport } from './routes/_site.compliance'
import { Route as SiteArchitectureRouteImport } from './routes/_site.architecture'

const TryRoute = TryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const SchrijvenRoute = SchrijvenRouteImport.update({
  id: '/schrijven',
  path: '/schrijven',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrustRoute = SiteTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => SiteRoute,
} as any)
const SiteScenariosRoute = SiteScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => SiteRoute,
} as any)
const SitePipelineRoute = SitePipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOverRoute = SiteOverRouteImport.update({
  id: '/over',
  path: '/over',
  getParentRoute: () => SiteRoute,
} as any)
const SiteModesRoute = SiteModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFlagsRoute = SiteFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => SiteRoute,
} as any)
const SiteComplianceRoute = SiteComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => SiteRoute,
} as any)
const SiteArchitectureRoute = SiteArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRoute
  '/schrijven': typeof SchrijvenRoute
  '/try': typeof TryRoute
  '/architecture': typeof SiteArchitectureRoute
  '/compliance': typeof SiteComplianceRoute
  '/flags': typeof SiteFlagsRoute
  '/modes': typeof SiteModesRoute
  '/over': typeof SiteOverRoute
  '/pipeline': typeof SitePipelineRoute
  '/scenarios': typeof SiteScenariosRoute
  '/trust': typeof SiteTrustRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRoute
  '/schrijven': typeof SchrijvenRoute
  '/try': typeof TryRoute
  '/architecture': typeof SiteArchitectureRoute
  '/compliance': typeof SiteComplianceRoute
  '/flags': typeof SiteFlagsRoute
  '/modes': typeof SiteModesRoute
  '/over': typeof SiteOverRoute
  '/pipeline': typeof SitePipelineRoute
  '/scenarios': typeof SiteScenariosRoute
  '/trust': typeof SiteTrustRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRoute
  '/schrijven': typeof SchrijvenRoute
  '/try': typeof TryRoute
  '/_site/architecture': typeof SiteArchitectureRoute
  '/_site/compliance': typeof SiteComplianceRoute
  '/_site/flags': typeof SiteFlagsRoute
  '/_site/modes': typeof SiteModesRoute
  '/_site/over': typeof SiteOverRoute
  '/_site/pipeline': typeof SitePipelineRoute
  '/_site/scenarios': typeof SiteScenariosRoute
  '/_site/trust': typeof SiteTrustRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/schrijven'
    | '/try'
    | '/architecture'
    | '/compliance'
    | '/flags'
    | '/modes'
    | '/over'
    | '/pipeline'
    | '/scenarios'
    | '/trust'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/schrijven'
    | '/try'
    | '/architecture'
    | '/compliance'
    | '/flags'
    | '/modes'
    | '/over'
    | '/pipeline'
    | '/scenarios'
    | '/trust'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/schrijven'
    | '/try'
    | '/_site/architecture'
    | '/_site/compliance'
    | '/_site/flags'
    | '/_site/modes'
    | '/_site/over'
    | '/_site/pipeline'
    | '/_site/scenarios'
    | '/_site/trust'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRoute
  SchrijvenRoute: typeof SchrijvenRoute
  TryRoute: typeof TryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schrijven': {
      id: '/schrijven'
      path: '/schrijven'
      fullPath: '/schrijven'
      preLoaderRoute: typeof SchrijvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trust': {
      id: '/_site/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof SiteTrustRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/scenarios': {
      id: '/_site/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof SiteScenariosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pipeline': {
      id: '/_site/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof SitePipelineRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/over': {
      id: '/_site/over'
      path: '/over'
      fullPath: '/over'
      preLoaderRoute: typeof SiteOverRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/modes': {
      id: '/_site/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof SiteModesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/flags': {
      id: '/_site/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof SiteFlagsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/compliance': {
      id: '/_site/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof SiteComplianceRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/architecture': {
      id: '/_site/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof SiteArchitectureRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteArchitectureRoute: typeof SiteArchitectureRoute
  SiteComplianceRoute: typeof SiteComplianceRoute
  SiteFlagsRoute: typeof SiteFlagsRoute
  SiteModesRoute: typeof SiteModesRoute
  SiteOverRoute: typeof SiteOverRoute
  SitePipelineRoute: typeof SitePipelineRoute
  SiteScenariosRoute: typeof SiteScenariosRoute
  SiteTrustRoute: typeof SiteTrustRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteArchitectureRoute: SiteArchitectureRoute,
  SiteComplianceRoute: SiteComplianceRoute,
  SiteFlagsRoute: SiteFlagsRoute,
  SiteModesRoute: SiteModesRoute,
  SiteOverRoute: SiteOverRoute,
  SitePipelineRoute: SitePipelineRoute,
  SiteScenariosRoute: SiteScenariosRoute,
  SiteTrustRoute: SiteTrustRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRoute,
  SchrijvenRoute: SchrijvenRoute,
  TryRoute: TryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
